name: harmony

services:
  centrifugo:
    image: centrifugo/centrifugo:v4.1
    command: centrifugo --config=config.yml
    ports:
      - "8000:8000"
    volumes:
      - "./centrifugo/config.yml:/centrifugo/config.yml"

  mongo:
    restart: always
    image: mongo:6.0.5
    command: --replSet rs0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "./mongo/init:/docker-entrypoint-initdb.d"
      - mongo-data:/data/db

volumes:
  mongo-data:
  mongo-config:
