name: harmony

services:
  harmony:
    restart: always
    build:
      context: ..
    ports:
      - "127.0.0.1:25001:25001"
    volumes:
      - "../config:/harmony/config"
    depends_on:
      - mongo
      - centrifugo

  centrifugo:
    restart: always
    image: centrifugo/centrifugo:v4.1
    command: centrifugo --config=config.yml
    ports:
      - "127.0.0.1:25002:25002"
    volumes:
      - "./centrifugo/config.yml:/centrifugo/config.yml"

  mongo:
    restart: always
    image: mongo:6.0.5
    command: --replSet rs0 --bind_ip_all
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
  mongo-config:
