name: harmony

services:
  centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo --config=config.yml
    network_mode: host
    volumes:
      - "./centrifugo/config.yml:/centrifugo/config.yml"

  mongo:
    restart: always
    image: bitnami/mongodb:5.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_ADVERTISED_PORT_NUMBER=27017
    network_mode: host
    volumes:
      - mongo-data:/bitnami/mongodb

volumes:
  mongo-data:
