name: harmony

services:
  centrifugo:
    image: centrifugo/centrifugo:v4.1
    command: centrifugo --config=config.yml
    ports:
      - "8000:8000"
    volumes:
      - "./centrifugo/config.yml:/centrifugo/config.yml"

  mongo:
    restart: always
    image: mongo:6.0.5
    command: --replSet rs0
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
  mongo-config:
